extends: phd.yaml
primary: "fe8019"
fontName: "xos4 Terminus"
fontSize: 12
chineseFontName: WenQuanYi WenQuanYi Bitmap Song
chineseFontSize: 11
font: "-*-terminus-*-*-*-*-14-*-*-*-*-*-*-*"

files:
    bashrc.tpl: ~/.bashrc
    cava.tpl: ~/.config/cava/config
    dwm_config.tpl: ~/build/dwm/config.h
    gtk.css: ~/.config/gtk-3.0/gtk.css
    slock_config.tpl: ~/build/slock/config.h
    slstatus_config.h: ~/build/slstatus/config.h
    qutebrowser_config.py: ~/.config/qutebrowser/config.py
    shell.tpl: ~/.shell.sh
    vimrc.tpl: ~/.vimrc
    gvimrc: ~/.gvimrc
    vim_colorscheme.tpl: ~/.vim/colors/base16.vim
    xresources.tpl: ~/.Xresources
    xinitrc.tpl: ~/.xinitrc
    fcitx_config.tpl: ~/.config/fcitx/config
    fcitx_light_ui_config.tpl: ~/.config/fcitx/conf/fcitx-light-ui.config
    tmux.conf: ~/.tmux.conf
    fonts.conf: ~/.config/fontconfig/fonts.conf
