# vim keybindings
bindkey -v

# 10ms for key sequences
KEYTIMEOUT=1

# vi style incremental search
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward  

autoload -Uz compinit promptinit
compinit
promptinit

prompt grml

# Fix Base 16 colors
~/.shell.sh

# Aliases
alias vim='vim --servername vim'

# ROS
ros-start(){
docker run -it \
    --env="DISPLAY" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    -v /home/$(whoami)/ros:/ros \
    osrf/ros:lunar-desktop-full \
    bash -c "cp /ros/.bashrc /root/.bashrc && bash"
}
 
ros-connect(){
docker exec -ti $(docker ps -aq --filter ancestor=osrf/ros:lunar-desktop-full --filter status=running) bash
}
 
ros-clean(){
docker rm $(docker ps -aq --filter ancestor=osrf/ros:lunar-desktop-full --filter status=exited)
}
