extends: solarized-dark.yaml
fontName: "xos4 Terminess Powerline"
fontSize: 14
font: "-*-terminus-*-*-*-*-14-*-*-*-*-*-*-*"

files:
    cava.tpl: cava_config
    dwm.tpl: dwm_config.h
    qutebrowser.tpl: qutebrowser.conf
    shell.tpl: shell.sh
    vim.tpl: base16.vim
    xresources.tpl: Xresources
    xinitrc.tpl: xinitrc
